'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class agenda
    Public Property id_agenda As Integer
    Public Property hora_entrada As Nullable(Of System.TimeSpan)
    Public Property hora_salida As Nullable(Of System.TimeSpan)
    Public Property dia As String
    Public Property profesional As Long

    Public Overridable Property Personal As Personal

End Class
