'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Paciente
    Public Property Id As Integer
    Public Property id_obra_soc As Integer
    Public Property id_genero As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property dni As Long
    Public Property localidad As String
    Public Property provincia As String
    Public Property direccion As String
    Public Property telefono As Long
    Public Property fecha_alta As Date
    Public Property fecha_nac As Date
    Public Property email As String
    Public Property deBaja As Boolean

    Public Overridable Property Genero As Genero
    Public Overridable Property Obra_Social As Obra_Social
    Public Overridable Property turnos As ICollection(Of turnos) = New HashSet(Of turnos)
    Public Overridable Property Historia_Clinica As ICollection(Of Historia_Clinica) = New HashSet(Of Historia_Clinica)

End Class
