'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Personal
    Public Property dni As Long
    Public Property cod_tipo_personal As Integer
    Public Property id_obra_soc As Integer
    Public Property id_genero As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property fecha_nac As Date
    Public Property fecha_ingreso As Date
    Public Property localidad As String
    Public Property provincia As String
    Public Property domicilio As String
    Public Property num_tel As Long
    Public Property email As String
    Public Property deBaja As Boolean

    Public Overridable Property Genero As Genero
    Public Overridable Property Obra_Social As Obra_Social
    Public Overridable Property Tipo_Personal As Tipo_Personal
    Public Overridable Property Usuario As ICollection(Of Usuario) = New HashSet(Of Usuario)
    Public Overridable Property agenda As ICollection(Of agenda) = New HashSet(Of agenda)
    Public Overridable Property turnos As ICollection(Of turnos) = New HashSet(Of turnos)
    Public Overridable Property Historia_Clinica As ICollection(Of Historia_Clinica) = New HashSet(Of Historia_Clinica)

End Class
