'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class turnos
    Public Property nro_turno As Integer
    Public Property fecha As Date
    Public Property hora As Date
    Public Property paciente As Integer
    Public Property profesional As Long
    Public Property deBaja As Boolean
    Public Property monto As Nullable(Of Decimal)
    Public Property monto_final As Nullable(Of Decimal)

    Public Overridable Property Paciente1 As Paciente
    Public Overridable Property Personal As Personal

End Class
