'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property dni As Long
    Public Property id_tipo_usuario As Integer
    Public Property username As String
    Public Property password As String
    Public Property deBaja As Boolean

    Public Overridable Property Personal As Personal
    Public Overridable Property Tipo_Usuario As Tipo_Usuario

End Class
